Feat/plugin descriptor json scheme generator
AllayMC/Allay pull request #422
Opened 2024-10-01 12:11 UTC by Cdm2883

2024-10-01 13:06 UTC, smartcmd requested changes

2024-10-01 13:06 UTC, smartcmd commented on codegen/build.gradle.kts
> +    implementation(project(":server"))
codegen shouldn't depends on server

2024-10-02 12:02 UTC, Cdm2883 commented
呜呜呜

2024-10-02 14:37 UTC, Cdm2883 reviewed
呜呜呜

2024-10-02 14:38 UTC, Cdm2883 commented
@smartcmd 呜呜呜

2024-10-02 14:40 UTC, YoumiHaLH commented
> @smartcmd 呜呜呜

呜呜呜呜呜

2024-10-02 14:57 UTC, Cdm2883 commented
> > @smartcmd 呜呜呜
> 
> 呜呜呜呜呜

呜哇哇哇

2024-10-02 16:44 UTC, Cdm2883 commented
https://gist.github.com/Cdm2883/79e6e6ed371c9346c5d4914fea6a687c

2024-10-03 05:56 UTC, merged