feat: add EntityUndeadComponent
AllayMC/Allay pull request #432
Opened 2024-10-04 14:40 UTC by heyhey123-git

2024-10-04 15:11 UTC, smartcmd requested changes

2024-10-04 15:11 UTC, smartcmd commented on api/src/main/java/org/allaymc/api/entity/data/EntityId.java
> +    ZOMBIFIED_PIGLIN("minecraft:zombie_pigman", 36),
This file is auto-generated, why you edit it?

2024-10-04 15:11 UTC, smartcmd commented on api/src/main/java/org/allaymc/api/entity/component/EntityUndeadComponent.java
> +public interface EntityUndeadComponent extends EntityBaseComponent {
Should extends EntityCompoent rather than EntityBaseComponent

2024-10-04 15:11 UTC, smartcmd commented on server/src/main/java/org/allaymc/server/entity/type/EntityTypeDefaultInitializer.java
> +    public static void initZombifiedPiglin() {
This file is auto-generated too

2024-10-05 05:35 UTC, smartcmd approved these changes

2024-10-05 05:36 UTC, smartcmd requested changes

2024-10-05 05:36 UTC, smartcmd commented on api/src/main/java/org/allaymc/api/entity/type/EntityTypes.java
> +    public static EntityType<EntityZombifiedPiglin> ZOMBIFIED_PIGLIN;
rename to the old name

2024-10-05 11:05 UTC, IWareQ requested changes
The `EntityZombiePigman` file is still deleted, please return it

2024-10-10 10:35 UTC, smartcmd commented on api/src/main/java/org/allaymc/api/entity/component/EntityUndeadComponent.java
> +    void setCatchesFireUnderSunlight(boolean catchesFireUnderSunlight);
I think the setter method can be removed, how you think?

2024-10-10 11:32 UTC, merged