feat: refine the behaviour of potion effects
AllayMC/Allay pull request #445
Opened 2024-10-11 11:06 UTC by heyhey123-git

#276

2024-10-11 11:14 UTC, smartcmd requested changes

2024-10-11 11:14 UTC, smartcmd commented on server/src/main/java/org/allaymc/server/entity/component/EntityDamageComponentImpl.java
> +        if (
why don't move this check to canBeAttacked()?

2024-10-11 11:40 UTC, smartcmd approved these changes

2024-10-11 11:40 UTC, smartcmd commented on server/src/main/java/org/allaymc/server/entity/component/EntityBaseComponentImpl.java
> +        return new HashMap<>(effects);
Use UnmodificalMap here and add @UnmodificalView annotation to interface

2024-10-11 11:42 UTC, smartcmd requested changes
qwq

2024-10-11 13:32 UTC, heyhey123-git commented
> qwq

qwq

2024-10-12 03:10 UTC, smartcmd approved these changes

2024-10-12 03:11 UTC, merged