fix: tall & short grass bugs
AllayMC/Allay pull request #483
Opened 2024-11-10 11:11 UTC by Dhaiven

This pr fix:
- tallgrass placement
- tallgrass drops (drop short grass if broken by shears, see https://minecraft.wiki/w/Tall_Grass#Breaking)
- tallgrass don't drop if broken by block

2024-11-10 11:19 UTC, smartcmd requested changes
Why don't edit block's loottable? https://github.com/AllayMC/Allay/blob/master/server/src/main/java/org/allaymc/server/loottable/condition/MatchToolCondition.java

https://github.com/AllayMC/Allay/blob/master/data/resources/loot_tables/blocks.json

2024-12-01 17:44 UTC, Dhaiven commented
Since we don't use loottables anymore, i revert last 3 commits.

2024-12-02 00:29 UTC, smartcmd approved these changes

2024-12-02 00:30 UTC, smartcmd commented
LGTM!

2024-12-02 00:30 UTC, merged