feat: impl trapdoor
AllayMC/Allay pull request #534
Opened 2024-12-30 12:26 UTC by harry-xi

2024-12-30 16:11 UTC, smartcmd commented
LGTM

2024-12-31 02:32 UTC, kanisonpoon commented
hmm Copper Trapdoor?

2024-12-31 02:58 UTC, harry-xi commented
> hmm Copper Trapdoor?

I well impl them later with the copper door but not in this pr.

2024-12-31 08:28 UTC, IWareQ approved these changes

2024-12-31 08:32 UTC, smartcmd requested changes

2024-12-31 08:32 UTC, smartcmd commented on server/src/main/java/org/allaymc/server/block/component/trapdoor/BlockIronTrapdoorBaseComponentImpl.java
> +        return true;
Hmm why return `true` here

2024-12-31 09:34 UTC, harry-xi commented on server/src/main/java/org/allaymc/server/block/component/trapdoor/BlockIronTrapdoorBaseComponentImpl.java
> +        return true;
The impl of door return a `true` here.

2024-12-31 09:53 UTC, smartcmd commented on server/src/main/java/org/allaymc/server/block/component/trapdoor/BlockIronTrapdoorBaseComponentImpl.java
> +        return true;
hmm that's not currect

2025-01-01 08:52 UTC, merged